# Auto-generated hardware configuration for AKATOSH host
# Do not modify this file! It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6d10c5b1-11b3-41db-abc3-bee75dd4e317";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4B60-FA47";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/hdd" = {
    device = "/dev/disk/by-uuid/77ecedd3-5c18-40a4-8c06-c38e800f4a3e";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-38f9f91f-0d1c-4975-b475-336ab53794a0".device =
    "/dev/disk/by-uuid/38f9f91f-0d1c-4975-b475-336ab53794a0";

  fileSystems."/mnt/ssd" = {
    device = "/dev/disk/by-uuid/754eae62-97a2-4290-937a-76bfa27f061e";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-2333fcc7-d73c-4975-b810-49cb4b281e78".device =
    "/dev/disk/by-uuid/2333fcc7-d73c-4975-b810-49cb4b281e78";

  swapDevices = [ ];

  # Networking configuration
  networking.useDHCP = lib.mkDefault true;

  # Platform-specific settings
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
