# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/root";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/675bf337-7549-4adc-8346-31997c7c5d8e";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3B84-27A0";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/var/lib/lxd/shmounts" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  fileSystems."/var/lib/lxd/devlxd" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  fileSystems."/mnt/small-ssd" = {
    device = "/dev/mapper/small-ssd";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."small-ssd".device =
    "/dev/disk/by-uuid/a459ee00-bd13-48a0-86ee-2cf55055d1ac";

  fileSystems."/mnt/ssd" = {
    device = "/dev/mapper/ssd";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."ssd".device = "/dev/disk/by-uuid/2333fcc7-d73c-4975-b810-49cb4b281e78";

  fileSystems."/mnt/hdd" = {
    device = "/dev/mapper/hdd";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."hdd".device = "/dev/disk/by-uuid/38f9f91f-0d1c-4975-b475-336ab53794a0";

  swapDevices = [
    { device = "/dev/mapper/swap"; }
  ];

  boot.initrd.luks.devices."swap".device = "/dev/disk/by-uuid/3c8afd79-473e-4fa0-a2b8-a86069ba20d3";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
